### ISSUE TITLE
Astro Build Hangs Indefinitely

### ISSUE THREAD

**Issue by mark-mybaggage** [astro-community/AstroCompress#181]
When building a static site with AstroCpmpress the build hangs indefinitely.  Typically, we build using GitHub Actions, however the same behaviour is observed locally.  I've attached several log files:

- logs_106.zip - logs from GitHub Action run
- local.txt - log from running locally

My packages.json file is:

```
{
  "name": "mb-pages",
  "type": "module",
  "version": "0.0.14",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "astro": "^2.10.14",
    "astro-compress": "^2.0.14",
    "nanoid": "^4.0.2",
    "node-html-parser": "^6.1.6"
  },
  "prettier": {
    "printWidth": 150,
    "trailingComma": "none",
    "semi": false
  },
  "devDependencies": {
    "@11ty/eleventy-img": "^3.1.0",
    "@types/node": "^20.5.7"
  }
}
```

The run command is:

```
npm run build
```

The last line logged is:

_Successfully compressed a total of 17 JavaScript files for 2.08 KB._

However, the build does not proceed any further nor is any error or warning logged

[logs_106.zip](https://github.com/astro-community/AstroCompress/files/12473482/logs_106.zip)
[local.txt](https://github.com/astro-community/AstroCompress/files/12473483/local.txt)

**Comment by NikolaRHristov** [comment]
It seems that image compression takes a while and this is why it gives the feeling of hanging. Can you try `Image: false` in the compression settings and see if that's the cause.

**Comment by mark-mybaggage** [comment]
I should have included my astro.config.mjs, apologies for that.  Here it is:

```
import { defineConfig } from 'astro/config';

import compress from "astro-compress";

// https://astro.build/config
export default defineConfig({
  integrations: [compress({
    css: false,
    html: true,
    js: false,
    img: false,
    svg: false,
  })]
});
```

Based on this it should only be doing HTML, however it appears that it has compressed the JavaScript - which it shouldn't have done?  I'll change this to the following and re-run (looks like some changes in case that I didn't notice previously):

```
import { defineConfig } from 'astro/config';

import compress from "astro-compress";

// https://astro.build/config
export default defineConfig({
  integrations: [compress({
    CSS: false,
    HTML: true,
    Image: false,
    JavaScript: false,
    SVG: false,
  })]
});
```

**Comment by NikolaRHristov** [comment]
Does it still hang with the new changes?

**Comment by NikolaRHristov** [comment]
The JavaScript is compressed by default fromvite, astro-compress just compresses one more time, plus the files you might have in public.

**Comment by mark-mybaggage** [comment]
Thanks for your prompt feedback - the build is completing as normal now.
