### ISSUE TITLE
EACCES: permission denied, scandir '/var/agentx' when try to build astro project

### ISSUE THREAD

**Issue by CreativeSight** [astro-community/AstroCompress#207]
I found this plugin and I want it in my project :) 
Trying to build astro project via npm run build locally on MacOS Ventura 13.6 or on Netlify got below error on the end:

 **EACCES: permission denied, scandir '/var/agentx'**

Tried to find solution and proposed is to use NPM in version >= 9

Dependencies versions:
Astro 3.3.2
Astro-compress 2.1.3
Node 18.18.0 
NPM 10.2.1

**Comment by NikolaRHristov** [comment]
Roll back to `v2.0.15` for now.
