### ISSUE TITLE
EACCES: permission denied, scandir '/lost+found' and also on others:EACCES: permission denied, scandir '/root'

### ISSUE THREAD

**Issue by ThanosYeah** [astro-community/AstroCompress#208]
i try to run astro build run and it seems after some debugging that astro-compress is the reason,what to do,package,json:{
  "name": "website",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro",
    "lint": "prettier --write  \"**/*.{js,jsx,ts,tsx,md,mdx,astro}\""
  },
  "dependencies": {
   
    "@astrojs/prefetch": "^0.4.0",
    "@astrojs/sitemap": "^3.0.2",
    "astro": "^3.3.2",
    "astro-compress": "^2.0.15",
    "astro-google-fonts-optimizer": "^0.2.2",
    "astro-purgecss": "^3.2.1",
    "astrojs-service-worker": "^1.1.0"
    
  },
  "devDependencies": {
    "prettier": "^3.0.3",
    "prettier-plugin-astro": "^0.12.0"
  }
}
astro.config.mjs:import { defineConfig } from 'astro/config';

import compress from "astro-compress";
import serviceWorker from "astrojs-service-worker";
// https://astro.build/config
import prefetch from "@astrojs/prefetch";
import sitemap from '@astrojs/sitemap';
import purgecss from 'astro-purgecss';
// https://astro.build/config
export default defineConfig({
 
  site: "https://mysite",
  
  
  
  integrations: [serviceWorker(), compress(), prefetch(), sitemap(), 
    purgecss({
    fontFace: true,
    keyframes: true,
    safelist: ['random', 'yep', 'button', /^nav-/],
    blocklist: ['usedClass', /^nav-/]
  })]
}); (it shows the same with the latest version)

**Comment by ThanosYeah** [comment]
i dont know if it is useful or not,when i use astro-compress 2.0.12 it works

**Comment by solelychloe** [comment]
Can reproduce. Running `astro-compress@^2.1.3`.
Getting this error when building: `Error: EACCES: permission denied, scandir '/lost+found'`

**Comment by NikolaRHristov** [comment]
Yes, there have been issues with the latest versions and they're deprecated for now use `2.0.15` as the latest one https://www.npmjs.com/package/astro-compress?activeTab=versions

**Comment by NikolaRHristov** [comment]
They are now also unpublished, I forgot I can do that.

**Comment by NikolaRHristov** [comment]
I'm closing this as those versions will not be re-published.

**Comment by igorskyflyer** [comment]
Also, I would like to leave this here, if you don't mind. 😌  

– If anyone is using Cloudflare (like I do), Netlify or some similar platform and has upgraded astro-compress to `> v2.0.15` (prior to those versions being unpublished), you will get the same error as mentioned here, on your host/platform.

The only fix for now is - as mentioned - to downgrade to `v2.0.15` and your builds will work again. 🥳👋🏼

**Comment by ThanosYeah** [comment]
> mentioned here, on your host/platform.\n\nThe only fix 

Yes, I was forced to use 2.0.13
