### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by SyedMuzamilM** [astro-community/AstroCompress#244]
```
[vite] Error when evaluating SSR module /opt/buildhome/repo/astro.config.mjs: failed to import "astro-compress"
11:18:19.066	|- Error: Could not load the "sharp" module using the linux-x64 runtime
11:18:19.067	Possible solutions:
11:18:19.067	- Add platform-specific dependencies:
11:18:19.067	    npm install --os=linux --cpu=x64 sharp
11:18:19.068	  or
11:18:19.068	    npm install --force @img/sharp-linux-x64
11:18:19.068	- Consult the installation documentation: https://sharp.pixelplumbing.com/install
11:18:19.068	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/sharp/lib/sharp.js:85:9)
11:18:19.068	    at Module._compile (node:internal/modules/cjs/loader:1233:14)
11:18:19.068	    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
11:18:19.068	    at Module.load (node:internal/modules/cjs/loader:1091:32)
11:18:19.069	    at Module._load (node:internal/modules/cjs/loader:938:12)
11:18:19.069	    at Module.require (node:internal/modules/cjs/loader:1115:19)
11:18:19.069	    at require (node:internal/modules/helpers:119:18)
11:18:19.069	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/sharp/lib/constructor.js:10:1)
11:18:19.069	    at Module._compile (node:internal/modules/cjs/loader:1233:14)
11:18:19.069	    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
11:18:19.069	
11:18:19.069	[astro] Unable to load your Astro config
11:18:19.069	
11:18:19.538	Could not load the "sharp" module using the linux-x64 runtime
11:18:19.539

```

**Comment by NikolaRHristov** [comment]
Hi, @SyedMuzamilM, can you provide more information on your environment, the OS, hosting provider, stuff like that, so that I can investigate it further? In the meantime, you can try running the #no-sharp branch, which disables image compression, but removes this error. To install it just replace the `package.json` entry for `astro-compress` with:

```json
{
    "astro-compress": "astro-community/AstroCompress#no-sharp"
}
```

**Comment by NikolaRHristov** [comment]
Which Node version are you using?

**Comment by NikolaRHristov** [comment]
There are similar issues in the sharp repository. Maybe try `npm ls sharp` as per https://github.com/lovell/sharp/issues/3896#issuecomment-1857516925 and see if there's a version mismatch somewhere in your code or with an outdated dependency.

**Comment by SyedMuzamilM** [comment]
> Which Node version are you using?

I am using the latest node version 20.10.0

**Comment by SyedMuzamilM** [comment]
> There are similar issues in the sharp repository. Maybe try `npm ls sharp` as per https://github.com/lovell/sharp/issues/3896#issuecomment-1857516925 and see if there's a version mismatch somewhere in your code or with an outdated dependency.

Will check the and see if this works. 

The previous command worked fine which doesn't use sharp. It is now getting deployed properly. 

Will check id any other dependency is using sharp so that the error could be resolved.

**Comment by NikolaRHristov** [comment]
I see, `astro` 3.6.4 is running an older version of `sharp` than `astro-compress`

```
├─┬ astro-compress@2.2.5
│ └── sharp@0.33.0
└─┬ astro@3.6.4
└── sharp@0.32.6
```

Can you try pinning the version of `sharp` for `astro` with the same one `astro-compress` uses. This is done by updating the `package.json` to override the dependency like so:

**package.json**

```json
{
  "name": "your-project",
  "version": "1.0.0",
  "dependencies": {
    "astro": "3.6.4",
    "astro-compress": "2.2.5"
  },
  "resolutions": {
    "sharp": "0.33.0"
  }
}
```

or

**package.json**

```json
{
  "overrides": {
    "astro": {
      "sharp": "0.33.0"
    }
  }
}
```

**Comment by SyedMuzamilM** [comment]
Since `astro:image` uses sharp as its default image service, I think that might be causing issues when using `astro-compress` 

[https://docs.astro.build/en/guides/images/#default-image-service](Astro Default Image Service) you can check it here.

**Comment by jpkhawam** [comment]
> Can you try pinning the version of `sharp` for `astro` with the same one `astro-compress` uses? This is done by updating the `package.json` to override the dependency like so:
> 
> **package.json**
> 
> ```json
>   "resolutions": {
>     "sharp": "0.33.0"
>   }
> ```

This fixed it for me! Thank you for your work

**Comment by kswedberg** [comment]
Interesting…  setting `"resolutions": {"sharp": "0.32.6"}` worked with my M1 MacBook Air, but setting it to `0.33.0` resulted in the error:

```
[vite] Error when evaluating SSR module /Users/kswedberg/Sites/ks/blog.karlswedberg.com/astro.config.mjs: failed to import "astro-compress"
|- Error: Could not load the "sharp" module using the darwin-arm64 runtime
```

**Comment by NikolaRHristov** [comment]
> Interesting… setting `"resolutions": {"sharp": "0.32.6"}` worked with my M1 MacBook Air, but setting it to `0.33.0` resulted in the error:
> 
> ```
> [vite] Error when evaluating SSR module /Users/kswedberg/Sites/ks/blog.karlswedberg.com/astro.config.mjs: failed to import "astro-compress"
> |- Error: Could not load the "sharp" module using the darwin-arm64 runtime
> ```

Use

```json
{
  "overrides": {
    "astro": {
      "sharp": "0.33.0"
    }
  }
}
```

`resolutions` is supported only on Yarn.

**Comment by kswedberg** [comment]
@NikolaRHristov , I'm using Yarn. Thanks for the suggestion, but neither `resolutions` nor `overrides` worked with sharp 0.33.0. Maybe I need to leave it set as `"resolutions": {"sharp": "0.32.6"}` — unless you have another idea I can try.

**Comment by NikolaRHristov** [comment]
> @NikolaRHristov , I'm using Yarn. Thanks for the suggestion, but neither `resolutions` nor `overrides` worked with sharp 0.33.0. Maybe I need to leave it set as `"resolutions": {"sharp": "0.32.6"}` — unless you have another idea I can try.

Well, the version of `sharp` depends on the `AstroCompress` and `Astro` versions and whichever you choose to override. I'm just suggesting `overrides` as a general solution since `resolutions` is only supported on Yarn.

**Comment by NikolaRHristov** [comment]
I'll see if I can implement something dynamic that overrides the `AstroCompress` version pre-install to match `Astro`'s sharp version.

**Comment by kswedberg** [comment]
> Well, the version of sharp depends on the AstroCompress and Astro versions and whichever you choose to override

Yeah, I get that. All I'm saying is that `astro build` fails with the error when I "choose to override" using `0.33.0`, while it works with `0.32.6`. In case it helps at all, I'm using astro 3.4.0 and astro-compress 2.2.5. And here is the (truncated) stdout of `yarn why sharp`:

```
=> Found "sharp@0.33.0"
info Reasons this module exists
   - "astro-compress" depends on it
   - Hoisted from "astro-compress#sharp"

=> Found "astro#sharp@0.32.6"
info This module exists because "astro" depends on it.
```

> I'll see if I can implement something dynamic that overrides the AstroCompress sharp version pre-install to match Astro's sharp version.

That would be wonderful. Thanks so much!

**Comment by NikolaRHristov** [comment]
> ```json
> {
>   "overrides": {
>     "astro-compress": {
>       "sharp": "0.32.6"
>     }
>   }
> }
> ```

Does this work?

**Comment by kswedberg** [comment]
No, `"overrides": {"astro-compress": {"sharp": "0.32.6"}}` didn't work for me. I'll just keep using `"resolutions": {"sharp": "0.32.6"}` until some later version irons out the issues. thanks again

**Comment by NikolaRHristov** [comment]
> No, `"overrides": {"astro-compress": {"sharp": "0.32.6"}}` didn't work for me. I'll just keep using `"resolutions": {"sharp": "0.32.6"}` until some later version irons out the issues. thanks again

@kswedberg I'm sorry, can I use you to debug something else? Does the resolutions work for `sharp` `0.33.1`?

**Comment by kswedberg** [comment]
No problem, happy to help. Trying it with `"resolutions": {"sharp": "0.33.1"}` did not work, unfortunately. `astro build` produced this:

```
12:29:08 PM [vite] Error when evaluating SSR module /Users/kswedberg/Sites/ks/blog.karlswedberg.com/astro.config.mjs: failed to import "astro-compress"
|- Error: Could not load the "sharp" module using the darwin-arm64 runtime
Possible solutions:

... [a bunch of stuff] ...

[astro] Unable to load your Astro config
 error   Could not load the "sharp" module using the darwin-arm64 runtime

```

**Comment by NikolaRHristov** [comment]
Thank you so much! We will investigate this further, for now glad that the resolutions hotfix works.
