### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by FabriceSalvaire** [astro-community/AstroCompress#270]
I got
```
generating optimized images
munmap_chunk(): invalid pointer
Abandon (core dumped)
```

**Comment by FabriceSalvaire** [comment]
oups it is related to asto...

**Comment by michaeltoohig** [comment]
> oups it is related to asto...

@FabriceSalvaire could you explain what you meant by this comment? For the rest of us could you say what you did to solve the issue then? Thank you for any further details you have.
