### ISSUE TITLE
Hydration completed but contains mismatches.

### ISSUE THREAD

**Issue by hayhaydz** [astro-community/AstroCompress#52]
Hey,

When I use this plugin I'm getting this error in my console:
<img width="722" alt="Screenshot 2022-11-11 at 10 15 36" src="https://user-images.githubusercontent.com/11842795/201319127-a004ddd8-1399-4ed0-af8b-0ce8b61218be.png">

Through a little bit of Googling I came across this same error here [https://github.com/vuejs/vitepress/issues/1143](https://github.com/vuejs/vitepress/issues/1143) and so I'm lead to believe that it is something to do with minifying the HTML when used with Vite and Vue.

**Comment by hayhaydz** [comment]
I can confirm that if I disable compression on just HTML the error disappears. Using the codes as below:

```js
compress({
	html: false,
}),
```

**Comment by nikolaxhristov** [comment]
Try:

```ts

import compress from "astro-compress";

export default {

	integrations: [
		compress({
			html: {
				collapseWhitespace: false,
				removeScriptTypeAttributes: false,
				trimCustomFragments: false
			},
		}),
	],
};

```

**Comment by nikolaxhristov** [comment]
I believe this is related to the `customEventAttributes` option from `html-minifier-terser` https://github.com/terser/html-minifier-terser

If you try:

```ts
import compress from "astro-compress";

export default {

	integrations: [
		compress({
			html: {
				collapseWhitespace: false,
				removeScriptTypeAttributes: false,
				trimCustomFragments: false,
				customEventAttributes: [ /^on[a-z]{3,}$/ ]
			},
		}),
	],
};
```

Because that's what Vue uses.

**Comment by nikolaxhristov** [comment]
These are the defaults with which `astro-compress` is working:

```ts
import compress from "astro-compress";

export default {

	integrations: [
		compress({
			html: {
				caseSensitive: true,
				collapseInlineTagWhitespace: false,
				collapseWhitespace: true,
				continueOnParseError: true,
				html5: true,
				includeAutoGeneratedTags: true,
				keepClosingSlash: true,
				minifyCSS: true,
				minifyJS: true,
				minifyURLs: false,
				preventAttributesEscaping: false,
				processConditionalComments: true,
				removeAttributeQuotes: true,
				removeComments: false,
				removeScriptTypeAttributes: true,
				removeStyleLinkTypeAttributes: true,
				removeTagWhitespace: false,
				sortAttributes: true,
				sortClassName: true,
				trimCustomFragments: true,
				useShortDoctype: false,
				noNewlinesBeforeTagClose: true,
				quoteCharacter: '"',
			},
		}),
	],
};
```

**Comment by nikolaxhristov** [comment]
Oh, but that is usual? https://github.com/vuejs/vitepress/issues/1143 It hydrates, but just the output doesn't match the original. This is normal. I think just Vue shows you this error.

**Comment by hayhaydz** [comment]
I appreciate the prompt response! Hmm, for now it seems safer to just exclude minifying HTML and then I know that there's no chance of anything breaking, regardless of it being a phantom error or not. I'm just aware that this error could pop up for other people that are using this integration with Vue.

**Comment by nikolaxhristov** [comment]
Maybe try

```ts
compress({
	html: {
		processConditionalComments: false
	}
})
```

because that's what Vue relies on.

**Comment by hayhaydz** [comment]
Unfortunately the error still persists

**Comment by nikolaxhristov** [comment]
Can you provide a reproduction?

**Comment by hayhaydz** [comment]
I can't get astro-compress to work with Stackblitz (https://stackblitz.com/edit/withastro-astro-xd43wq?file=README.md)[https://stackblitz.com/edit/withastro-astro-xd43wq?file=README.md]

**Comment by nikolaxhristov** [comment]
So, stackblitz doesn't have support for `sharp` which is used by `astro-compress` to compress images. I pulled the repo locally and successfully built it. No error was shown. I have setup a codesandbox for you https://github.com/nikolaxhristov/withastro-astro-xd43wq/tree/main/ you can view it from here: https://codesandbox.io/p/github/nikolaxhristov/withastro-astro-xd43wq/draft/elastic-waterfall?selection=%5B%7B%22endColumn%22%3A26%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A8%7D%5D&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cladb7b9k001al0gd6ga2bmxh%2522%252C%2522key%2522%253A%2522cladb7b1v01252a68fcx19k1b%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

Run `yarn build` and `yarn serve` in the console and you should see the full output

**Comment by nelhop** [comment]
I am facing the same issue.

Only thing that fixes the Vue component is disabling the compression for HTML, like @hayhaydz suggested:

> I can confirm that if I disable compression on just HTML the error disappears. Using the codes as below:
> 
> ```js
> compress({
>     html: false,
> }),
> ```

**Comment by nikolaxhristov** [comment]
Hi, can you paste an example of the HTML and what version of `astro-compress` are you using?

**Comment by nelhop** [comment]
I cannot reproduce this with the up to date version of `astro-compress`. Seems to be fixed.

**Comment by mortbauer** [comment]
I do not get why this is closed, can totally reproduce this with a minimal astro, vue example.

**Comment by ZermattChris** [comment]
> I do not get why this is closed, can totally reproduce this with a minimal astro, vue example.

I'm also getting this with a simple Astro page and a single Vue component using "<Flyout client:idle />". If I change it to '<Flyout client:only="vue" />' then the error is gone (but that's not quite how I wanted to hydrate this component).

**Comment by preetamslot** [comment]
@ZermattChris @mortbauer 
I had this issue before:
https://github.com/astro-community/AstroCompress/issues/11#issuecomment-1209355695

for me this worked:
```
HTML: {
        caseSensitive: true,
        collapseBooleanAttributes: true,
        collapseInlineTagWhitespace: false,
        collapseWhitespace: true,
        conservativeCollapse: false,
        continueOnParseError: false,
        customAttrAssign: [],
        customAttrCollapse: "",
        customAttrSurround: [],
        customEventAttributes: [/^on[a-z]{3,}$/],
        decodeEntities: false,
        html5: true,
        ignoreCustomComments: [],
        ignoreCustomFragments: [],
        includeAutoGeneratedTags: true,
        keepClosingSlash: true,
        maxLineLength: null,
        minifyCSS: true,
        minifyJS: true,
        minifyURLs: false,
        preserveLineBreaks: false,
        preventAttributesEscaping: false,
        processConditionalComments: true,
        processScripts: ["module"],
        quoteCharacter: "",
        removeAttributeQuotes: true,
        removeComments: false,
        removeEmptyAttributes: false,
        removeEmptyElements: false,
        removeOptionalTags: false,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        removeTagWhitespace: true,
        sortAttributes: true,
        sortClassName: true,
        trimCustomFragments: false,
        useShortDoctype: false,
      },
```

**Comment by NikolaRHristov** [comment]
> I do not get why this is closed, can totally reproduce this with a minimal astro, vue example.

Hello, @mortbauer, I am unable to reproduce this on https://stackblitz.com/edit/withastro-astro-4m4kmy

**Comment by NikolaRHristov** [comment]
Can you provide a more detailed example?
